REM *** COBXREF グローバル更新項目チェック ソート用
REM ===> FILEITEM.T015.POT1 で作成
COBXREF
COBSORT  COBSORT.T004.PRM1
FILEITEM FILEITEM.T015.PRM1 FILEITEM.0111.PRM2
DEL XREF.DEFREF
DEL XREF.SORT.DEFREF
DEL *.LST
