*>   GnuCOBOL 2.2 OCT2017 Sample Programs (A4).pdf

*>   3. Colors
*>   Colors is a handy little GnuCOBOL utility program that will produce a screen showing all
*>   possible combinations of:
*>   FOREGROUND-COLOR
*>   BACKGROUND-COLOR
*>   BLINKING (or absence of BLINKING)
*>   HIGHLIGHT, LOWLIGHT or absence of either (i.e. "Normal")
*>   REVERSE-VIDEO
*>  >>SOURCE FREE
  IDENTIFICATION DIVISION.
  PROGRAM-ID. colors.
  DATA DIVISION.
  WORKING-STORAGE         SECTION.
  01  WORK-AREA.
      03  WK-ACT     PIC  X(001) VALUE SPACE.

  SCREEN SECTION.
*>  01 S-COLORTST-SCR01 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 BLANK SCREEN.
  01 S-COLORTST-SCR00G.
  05 LINE 01.
  10 COL 1 VALUE ' LOWLIGHT -------- HIGHLIGHT LOWLIGHT -------- HIGHLIGHT'.

*>  01 S-COLORTST-SCR02 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
  05 LINE + 1.
   10 COL 1 VALUE ' -------- -------- -------- -------- -------- --------'.

*>  01 S-COLORTST-SCR03 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' -------- -------- -------- REVERSE REVERSE REVERSE'.

*>  01 S-COLORTST-SCR04 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' 01234567 01234567 01234567 01234567 01234567 01234567'.

*>  01 S-COLORTST-SCR05 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '0 0 0 0 0 0 '.

*>  01 S-COLORTST-SCR06 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '1 1 1 1 1 1 '.

*>  01 S-COLORTST-SCR07 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '2 2 2 2 2 2 '.

*>  01 S-COLORTST-SCR08 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '3 1 3 2 3 3 3 4 3 5 3 6 '.

*>  01 S-COLORTST-SCR09 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '4 4 4 4 4 4 '.

*>  01 S-COLORTST-SCR10 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '5 5 5 5 5 5 '.

*>  01 S-COLORTST-SCR11 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '6 6 6 6 6 6 '.

*>  01 S-COLORTST-SCR12 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '7 7 7 7 7 7 '.

*>  01 S-COLORTST-SCR13 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' LOWLIGHT -------- HIGHLIGHT LOWLIGHT -------- HIGHLIGHT'.

*>  01 S-COLORTST-SCR14 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' BLINK BLINK BLINK BLINK BLINK BLINK'.

*>  01 S-COLORTST-SCR15 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' -------- -------- -------- REVERSE REVERSE REVERSE'.

*>  01 S-COLORTST-SCR16 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE ' 01234567 01234567 01234567 01234567 01234567 01234567'.

*>  01 S-COLORTST-SCR17 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '0 0 0 0 0 0 '.

*>  01 S-COLORTST-SCR18 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '1 1 1 1 1 1 '.

*>  01 S-COLORTST-SCR19 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '2 2 2 2 2 2 '.

*>  01 S-COLORTST-SCR20 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '3 7 3 8 3 9 3 10 3 11 3 12 '.

*>  01 S-COLORTST-SCR21 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '4 4 4 4 4 4 '.

*>  01 S-COLORTST-SCR22 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '5 5 5 5 5 5 '.

*>  01 S-COLORTST-SCR23 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '6 6 6 6 6 6 '.

*>  01 S-COLORTST-SCR24 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 1 VALUE '7 7 7 7 7 7 '.

   *> #1

  01 S-COLORTST-SCR01G.
   05 LINE 05.
   10 COL 2 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 2 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 2 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 2 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
   05 LINE + 1.
   10 COL 2 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
   10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 2 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 2 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 2 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 LOWLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 LOWLIGHT VALUE 'X'.

    *> #2

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 05.
    10 COL 12 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 VALUE 'X'.
    05 LINE + 1.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    10 COL 12 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 VALUE 'X'.

    *> #3

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 05.
    10 COL 22 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT VALUE 'X'.

    *> #4

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 05.
    10 COL 32 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 LOWLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 LOWLIGHT REVERSE-VIDEO VALUE 'X'.

    *> #5

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 05.
    10 COL 42 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 REVERSE-VIDEO VALUE 'X'.

    *> #6

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 05.
    10 COL 52 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT REVERSE-VIDEO VALUE 'X'.

    *> #7

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 17.
    10 COL 02 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 02 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 LOWLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 LOWLIGHT BLINK VALUE 'X'.

    *> #8

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE 17.
    10 COL 12 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 12 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 BLINK VALUE 'X'.

    *> #9

  01 S-COLORTST-SCR09G.
    05 LINE 17.
    10 COL 22 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 22 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT BLINK VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT BLINK VALUE 'X'.

    *> #10

  01 S-COLORTST-SCR10G.
    05 LINE 17.
    10 COL 32 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 32 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

    *> #11

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
  01 S-COLORTST-SCR11G.
    05 LINE 17.
    10 COL 42 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 42 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 BLINK REVERSE-VIDEO VALUE 'X'.

    *> #12

*>  01 S-COLORTST-SCR12G BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
  01 S-COLORTST-SCR12G.
    05 LINE 17.
    10 COL 52 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

*>  01 S-COLORTST-SCR26 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7.
    05 LINE + 1.
    10 COL 52 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
    10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.

    PROCEDURE DIVISION.
    000-Main SECTION.

    DISPLAY S-COLORTST-SCR00G
    DISPLAY S-COLORTST-SCR01G
*>    GO 000-ACCEPT


    DISPLAY S-COLORTST-SCR09G
    DISPLAY S-COLORTST-SCR10G
    DISPLAY S-COLORTST-SCR11G
    DISPLAY S-COLORTST-SCR12G


    GO 000-ACCEPT

*>  DISPLAY S-COLORTST-SCR01
*>  DISPLAY S-COLORTST-SCR02
*>  DISPLAY S-COLORTST-SCR03
*>  DISPLAY S-COLORTST-SCR04
*>  DISPLAY S-COLORTST-SCR05
*>  DISPLAY S-COLORTST-SCR06
*>  DISPLAY S-COLORTST-SCR07
*>  DISPLAY S-COLORTST-SCR08
*>  DISPLAY S-COLORTST-SCR09
*>  DISPLAY S-COLORTST-SCR10

*>  GO 000-ACCEPT

*>  DISPLAY S-COLORTST-SCR11
*>  DISPLAY S-COLORTST-SCR12
*>  DISPLAY S-COLORTST-SCR13
*>  DISPLAY S-COLORTST-SCR14
*>  DISPLAY S-COLORTST-SCR15
*>  DISPLAY S-COLORTST-SCR16
*>  DISPLAY S-COLORTST-SCR17
*>  DISPLAY S-COLORTST-SCR18
*>  DISPLAY S-COLORTST-SCR19
*>  DISPLAY S-COLORTST-SCR20
*>  DISPLAY S-COLORTST-SCR21
*>  DISPLAY S-COLORTST-SCR22
*>  DISPLAY S-COLORTST-SCR23
*>  DISPLAY S-COLORTST-SCR24
*>  DISPLAY S-COLORTST-SCR25
*>    DISPLAY S-COLORTST-SCR26
.

000-ACCEPT.
    ACCEPT WK-ACT LINE 25 COL 1
    .
000-EX.
    STOP RUN
    .
